apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-auth-gateway
  namespace: demo-auth
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 15021
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-auth-vservice
  namespace: demo-auth
spec:
  hosts:
  - "*"
  gateways:
  - demo-auth-gateway
  http:
  - match:
    - uri:
        exact: /register
    - uri:
        prefix: /auth
    - uri:
        exact: /login
    - uri:
        prefix: /auth
    - uri:
        exact: /update_my_password
    - uri:
        prefix: /auth
    - uri:
        exact: /
    - uri:
        prefix: /
    - uri:
        exact: /products
    - uri:
        prefix: /api/v1
  - destination:
        host: demo-auth-service